var b = 'Welcome to TypeScript, AKHIL';
console.log(b);
var x = 10;
var y = 20;
console.log(x + y);
var first_Name = 'akhil';
console.log(first_Name);
console.log(typeof (first_Name));
var c = 20.000;
console.log(typeof (c));
var d = true;
console.log(typeof (d));
var e;
console.log(typeof (e));
